Module1 task2
htmlacademy-php/1870651-yeticave-12 pull request #3
Opened 2021-08-14 09:22 UTC by R3g1tpr0cs

2021-08-14 09:26 UTC, dshemin requested changes

2021-08-14 09:26 UTC, dshemin commented on index.php
> +	<div class="user-menu__logged">
Пожалуйста отформатируйте код так, чтобы было понятно что и в каком блоке находится. Очень трудно читать.

2021-08-14 09:26 UTC, dshemin commented on index.php
> +        <?php if ($is_auth == 1): ?>
Используйте строгое сравнение.

2021-08-14 10:38 UTC, R3g1tpr0cs commented on index.php
> +	<div class="user-menu__logged">
Редактирую файл в nano, там у меня всё нормально, строки не едут. Лучше использовать что-то другое?

2021-08-14 10:42 UTC, R3g1tpr0cs commented on index.php
> +        <?php if ($is_auth == 1): ?>
Исправил

2021-08-14 12:03 UTC, dshemin requested changes

2021-08-14 12:03 UTC, dshemin commented on index.php
> +	   <div class="user-menu__logged">
Форматирование поправьте пожалуйста. Это очень важно, говорю вам как разработчик с опытом. Ревьювить код с смешанным отступами - очень трудно.

2021-08-16 04:41 UTC, dshemin requested changes

2021-08-16 04:41 UTC, dshemin commented on index.php
> +            <?php if ($is_auth == 1): ?>
Уже лучше, но отступ тут и на строках `elseif` и `endif` отсупы другие. В PHP принято использовать 4 пробела для отступа.

2021-08-16 04:41 UTC, dshemin commented on index.php
> +            <?php if ($is_auth == 1): ?>
Сравнение должно быть строгим.

2021-08-16 04:42 UTC, dshemin commented on index.php
> +	<div class="user-menu__logged">
Проверьте что у вас смешанны табуляции и пробелы.

2021-08-17 03:09 UTC, dshemin requested changes

2021-08-17 03:09 UTC, dshemin commented on index.php
> +            <?php if ($is_auth == TRUE): ?>
Во-первых: `$is_auth` - это число которое может быть 0 или 1. Почему мы сравниваем с `TRUE`.
Во-вторых: всегда нужно использовать строгое сравнение.

2021-08-17 03:09 UTC, dshemin commented on index.php
> +	        <?php elseif ($is_auth == FALSE): ?>
`$is_auth` может быть либо 0, либо 1, поэтому `elseif` тут не нужен.

2021-08-17 03:09 UTC, dshemin commented on index.php
> +    	                <a href="#">Регистрация</a>
Эта ссылка находится внутри блока `li`. Соответственно она должна быть отформатирована так, чтобы это можно было увидеть визуально. С форматирование пока всё равно не очень, попробую проилюстрировать со своей точки зрения. Что легче воспринять?

Первый вариант:
```
<div>
<ul>
<li>
<?php
echo "foo"
?>
</li>
</ul>
</div>
```

или

Второй вариант:
```
<div>
   <ul>
<li>
          <?php
echo "foo"
?>
    </li>
</ul>
</div>
```
или

Третий вариант:
```
<div>
    <ul>
        <li>
            <?php
                echo "foo"
            ?>
        </li>
    </ul>
</div>
```

И это не придирки, в любом проекте, если там есть культура код ревью и код стайла, вам будут об этом писать.

Понятно, что делать это вручную - трудно и муторно. Но есть много разных IDE которые делают это автоматически. Попробуйте найти.

2021-08-18 01:45 UTC, dshemin requested changes

2021-08-18 01:45 UTC, dshemin commented on index.php
> +    	                <a href="#">Регистрация</a>
Обратите внимание на этот комментарий пожалуйста.

2021-08-19 02:13 UTC, dshemin approved these changes

2021-08-19 02:13 UTC, merged